/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostRequirementRouteImport } from './routes/post-requirement'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinusRouteImport } from './routes/joinus'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRequirementRoute = PostRequirementRouteImport.update({
  id: '/post-requirement',
  path: '/post-requirement',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinusRoute = JoinusRouteImport.update({
  id: '/joinus',
  path: '/joinus',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/joinus': typeof JoinusRoute
  '/login': typeof LoginRoute
  '/post-requirement': typeof PostRequirementRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/providers': typeof ProvidersRoute
  '/requirements': typeof RequirementsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/booking/$id': typeof BookingIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/joinus': typeof JoinusRoute
  '/login': typeof LoginRoute
  '/post-requirement': typeof PostRequirementRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/providers': typeof ProvidersRoute
  '/requirements': typeof RequirementsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/booking/$id': typeof BookingIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/joinus': typeof JoinusRoute
  '/login': typeof LoginRoute
  '/post-requirement': typeof PostRequirementRoute
  '/profile': typeof ProfileRoute
  '/provider': typeof ProviderRoute
  '/providers': typeof ProvidersRoute
  '/requirements': typeof RequirementsRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/booking/$id': typeof BookingIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/joinus'
    | '/login'
    | '/post-requirement'
    | '/profile'
    | '/provider'
    | '/providers'
    | '/requirements'
    | '/services'
    | '/terms'
    | '/admin/analytics'
    | '/booking/$id'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/joinus'
    | '/login'
    | '/post-requirement'
    | '/profile'
    | '/provider'
    | '/providers'
    | '/requirements'
    | '/services'
    | '/terms'
    | '/admin/analytics'
    | '/booking/$id'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/joinus'
    | '/login'
    | '/post-requirement'
    | '/profile'
    | '/provider'
    | '/providers'
    | '/requirements'
    | '/services'
    | '/terms'
    | '/admin/analytics'
    | '/booking/$id'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  JoinusRoute: typeof JoinusRoute
  LoginRoute: typeof LoginRoute
  PostRequirementRoute: typeof PostRequirementRoute
  ProfileRoute: typeof ProfileRoute
  ProviderRoute: typeof ProviderRoute
  ProvidersRoute: typeof ProvidersRoute
  RequirementsRoute: typeof RequirementsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  BookingIdRoute: typeof BookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-requirement': {
      id: '/post-requirement'
      path: '/post-requirement'
      fullPath: '/post-requirement'
      preLoaderRoute: typeof PostRequirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/joinus': {
      id: '/joinus'
      path: '/joinus'
      fullPath: '/joinus'
      preLoaderRoute: typeof JoinusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  JoinusRoute: JoinusRoute,
  LoginRoute: LoginRoute,
  PostRequirementRoute: PostRequirementRoute,
  ProfileRoute: ProfileRoute,
  ProviderRoute: ProviderRoute,
  ProvidersRoute: ProvidersRoute,
  RequirementsRoute: RequirementsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  BookingIdRoute: BookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
